#!/bin/sh

remote="$1"
url="$2"

z40=0000000000000000000000000000000000000000

while read local_ref local_sha remote_ref remote_sha
do
    echo "Performing linter check"
    python tools/lint.py . --nproc=5 || exit 1
    echo "OK"
done

exit 0
