# SPDX-FileCopyrightText: Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Feature Request Form
description: Request new or improved functionality or changes to existing functionality
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!

  - type: dropdown
    id: new_or_improvement
    attributes:
      label: Is this a new feature, an improvement, or a change to existing functionality?
      options:
        - New Feature
        - Improvement
        - Change
    validations:
      required: true

  - type: dropdown
    id: criticality
    attributes:
      label: How would you describe the priority of this feature request
      options:
        - Must have (e.g. DALI adoption is impossible due to lack in functionality).
        - Should have (e.g. Adoption is possible, but the performance shortcomings make the solution inferior).
        - Nice to have (e.g. Adoption is possible, the feature will enhance the use-case even more).
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Please provide a clear description of problem this feature solves
      description: Real usage examples are especially helpful, non-code.
    validations:
      required: true

  - type: textarea
    id: Feature_Description
    attributes:
      label: Feature Description
      description: Please provide clear description of the feature you request (refer to [User Story format](https://www.atlassian.com/agile/project-management/user-stories#:~:text=User%20story%20template%20and%20examples) and [EARS format](https://ieeexplore.ieee.org/document/5328509))
      placeholder: >
        For new feature request, please use one of the following format to describe the feature
          1. From End-user perspective, use the following user story format
              As a <persona>, I <want to>, <so that>.
          2. From System perspective, use the following EARS format
              <Pre-Condition> <System> shall  <process> <object to be process> <condition>
        For changing or improving existing feature, it's recommended to provide the previous Feature Request ID.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe your ideal solution
      description: Please describe the functionality you would like added.
      placeholder: >
        A new function that takes in the information in this form, and triages the issue

        def feature_request(form_info):
            parse(form_info)
            return triage_outcome
        You can even provide a reference implementation in other library.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe any alternatives you have considered
      description: List any other libraries, or approaches you have looked at or tried.
      placeholder: I have looked at library xyz and qrs, but they do not offer GPU acceleration

  - type: textarea
    id: misc
    attributes:
      label: Additional context
      description: Add any other context, code examples, or references to existing implementations about the feature request here. If applicable, please list the modules affected.

  - type: checkboxes
    id: terms
    attributes:
      label: Check for duplicates
      options:
        - label: I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report
          required: true
