ARG TF_CUSTOM_OP_BUILDER_IMAGE
FROM ${TF_CUSTOM_OP_BUILDER_IMAGE} as base

WORKDIR /opt/dali

FROM base as base_with_wheel

COPY dali_tf_plugin/whl whl
RUN pip install whl/*.whl && rm -rf whl

FROM base_with_wheel

ARG NVIDIA_DALI_BUILD_FLAVOR
ENV NVIDIA_DALI_BUILD_FLAVOR=${NVIDIA_DALI_BUILD_FLAVOR}
ARG GIT_SHA
ENV GIT_SHA=${GIT_SHA}
ARG DALI_TIMESTAMP
ENV DALI_TIMESTAMP=${DALI_TIMESTAMP}
ARG NVIDIA_BUILD_ID
ENV NVIDIA_BUILD_ID ${NVIDIA_BUILD_ID:-0}

RUN mkdir /dali_tf_sdist && chmod 0777 /dali_tf_sdist

COPY Acknowledgements.txt .
COPY COPYRIGHT .
COPY LICENSE .
COPY VERSION .
COPY cmake cmake
COPY dali_tf_plugin dali_tf_plugin

WORKDIR /opt/dali/dali_tf_plugin

ENTRYPOINT /bin/bash build_in_custom_op_docker.sh