ARG TF_CUSTOM_OP_BUILDER_IMAGE="tensorflow/tensorflow:custom-op-gpu"
FROM ${TF_CUSTOM_OP_BUILDER_IMAGE}

WORKDIR /opt/dali_tf_build

ARG NVIDIA_DALI_BUILD_FLAVOR
ENV NVIDIA_DALI_BUILD_FLAVOR=${NVIDIA_DALI_BUILD_FLAVOR}
ARG GIT_SHA
ENV GIT_SHA=${GIT_SHA}
ARG DALI_TIMESTAMP
ENV DALI_TIMESTAMP=${DALI_TIMESTAMP}
ARG NVIDIA_BUILD_ID
ENV NVIDIA_BUILD_ID ${NVIDIA_BUILD_ID:-0}

RUN mkdir /dali_tf_sdist && chmod 0777 /dali_tf_sdist

COPY Acknowledgements.txt .
COPY COPYRIGHT .
COPY LICENSE .
COPY VERSION .
COPY cmake cmake
COPY dali_tf_plugin dali_tf_plugin

WORKDIR /opt/dali_tf_build/dali_tf_plugin

RUN pip install whl/*.whl

ENTRYPOINT /bin/bash build_in_custom_op_docker.sh