// Copyright (c) 2017-2018, NVIDIA CORPORATION. All rights reserved.

#include "dali/pipeline/operators/reader/mxnet_reader_op.h"

namespace dali {

DALI_REGISTER_OPERATOR(MXNetReader, MXNetReader, CPU);

DALI_SCHEMA(MXNetReader)
  .DocStr("Read sample data from a MXNet RecordIO")
  .NumInput(0)
  .NumOutput(2)
  .AddArg("path",
      R"code(`list of string`
      List of paths to RecordIO files)code")
  .AddArg("index_path",
      R"code(`list of string`
      List (of length 1) containing a path to index (.idx) file.
      It is generated by the MXNet's `im2rec.py` script
      together with RecordIO file. It can also be
      generated using `rec2idx` script distributed with DALI)code")
  .AddParent("LoaderBase");

}  // namespace dali

