# Copyright (c) 2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from enum import Enum

class DALIDataType(Enum):
    NO_TYPE = ...
    UINT8 = ...
    UINT16 = ...
    UINT32 = ...
    UINT64 = ...
    INT8 = ...
    INT16 = ...
    INT32 = ...
    INT64 = ...
    FLOAT16 = ...
    FLOAT = ...
    FLOAT64 = ...
    BOOL = ...
    STRING = ...
    DATA_TYPE = ...
    IMAGE_TYPE = ...
    INTERP_TYPE = ...

class DALIImageType(Enum):
    RGB = ...
    BGR = ...
    GRAY = ...
    YCbCr = ...
    ANY_DATA = ...

class DALIInterpType(Enum):
    INTERP_NN = ...
    INTERP_LINEAR = ...
    INTERP_CUBIC = ...
    INTERP_LANCZOS3 = ...
    INTERP_TRIANGULAR = ...
    INTERP_GAUSSIAN = ...
