name: Secret Scan

on:
  push:
    branches:
      - "pull-request/[0-9]+"
permissions:
  actions: read
  contents: read
  id-token: write
  security-events: write

jobs:
  secret-scan:
    uses: NVIDIA/security-workflows/.github/workflows/secret-scan-pulse.yml@031c5429271b5692e025c3e292fcc2bf11e116f7
    with:
      runs-on: linux-amd64-cpu4
